name: Docker Image

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  push:
    strategy:
      matrix:
        image: [
          {
            dockerfile: 'Dockerfile',
            tag: 'neovim'
          },
          {
            dockerfile: 'Dockerfile.tex',
            tag: 'neovim-tex'
          },
        ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file ${{ matrix.image.dockerfile }} --tag ${{ matrix.image.tag }} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/${{ matrix.image.tag }}
          docker tag ${{ matrix.image.tag }} $IMAGE_TAG
          docker push $IMAGE_TAG

      - name: Delete previous releases
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image.tag }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
