name: Docker Image

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  push:
    strategy:
      matrix:
        image: [
          {
            dockerfile: 'Dockerfile',
            tag: 'neovim'
          },
          {
            dockerfile: 'Dockerfile.tex',
            tag: 'neovim-tex'
          },
        ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.image.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.tag }}:latest
          labels: |
            runnumber=${GITHUB_RUN_ID}

      - name: Delete previous releases
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image.tag }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
